name: v2x-perception
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24
  - pandas>=2.0
  - shapely>=2.0
  - matplotlib>=3.7
  - scipy>=1.10
  - typing_extensions
  - pip
